server:
  port: 8081
spring:
  application:
    name: MessageProducer
  ## 和application平级，而不是在下级或者上级
  rabbitmq:
    # IP
    host: 192.168.31.77
    # 端口
    port: 5672
    # 用户名
    username: root
    # 密码
    password: root
    # 虚拟主机
    virtual-host: /MessageProject